root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "bash ../scripts/build-wasm.sh"
  delay = 1000
  exclude_dir = ["tmp"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  stop_on_error = false

[misc]
  clean_on_exit = false
